model_params:
  model: SimpleNet

args:
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 32
    num_workers: 0

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  stage1:
    state_params:
      num_epochs: &num_epochs 4

    optimizer_params:
      optimizer: Adam
      lr_linear_scaling:
        lr: 0.001
        base_batch_size: 64
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [1]
      gamma: 0.3

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1, 3, 5]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
